fail_fast: true

repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.9.4
    hooks:
      - id: uv-lock

  - repo: local
    hooks:
      - id: ruff-format
        name: Ruff Format
        entry: uv run --frozen ruff
        args: [format]
        language: system
        types: [python]
        pass_filenames: false
      - id: ruff
        name: Ruff
        entry: uv run --frozen ruff
        args: ["check", "--fix", "--exit-non-zero-on-fix"]
        types: [python]
        language: system
        pass_filenames: false
      # - id: pyright
      #   name: pyright
      #   entry: uv run --frozen pyright
      #   language: system
      #   types: [python]
      #   pass_filenames: false
      - id: uv-lock-check
        name: Check uv.lock is up to date
        entry: uv lock --check
        language: system
        files: ^(pyproject\.toml|uv\.lock)$
        pass_filenames: false