name: Dockerfile Lint

on:
  push:
    branches:
      - main
    paths:
      - project/Dockerfile.jinja
  pull_request:
    paths:
      - project/Dockerfile.jinja

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  hadolint:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v6

      - name: Lint Dockerfile with hadolint
        uses: hadolint/hadolint-action@v3.3.0
        with:
          dockerfile: project/Dockerfile.jinja
